Refactor install.sh and preinst scripts.

diff --git a/preinst b/preinst
--- a/preinst
+++ b/preinst
@@ -1,13 +1,14 @@
 #!/bin/bash
 
-# Extract and move icon
-mkdir -p /tmp/firefoxprofile_installer
-if [[ -e /usr/lib/firefox/browser/omni.ja ]]; then
-    unzip /usr/lib/firefox/browser/omni.ja -c "chrome/browser/skin/classic/browser/privatebrowsing/favicon.svg" -d /tmp/firefoxprofile_installer > /dev/null 2>&1
-else
-    unzip /usr/lib/firefox-esr/browser/omni.ja -c "chrome/browser/skin/classic/browser/privatebrowsing/favicon.svg" -d /tmp/firefoxprofile_installer > /dev/null 2>&1
-fi
+# Import install functions.
+source "./install.sh"
 
-sudo mkdir -p /usr/share/pixmaps/
-sudo mv /tmp/firefoxprofile_installer/chrome/browser/skin/classic/browser/privatebrowsing/favicon.svg /usr/share/pixmaps/private_browsing_firefox.svg
-rm -rf /tmp/firefoxprofile_installer
+echo "Preparing installation..."
+
+# Register a cleanup function to be called on the EXIT signal. Regardless of the exit code.
+trap handle_exit_signal EXIT
+
+# Extract and install private browsing icon.
+prepare_temp_dir
+determine_firefox_install_path
+install_private_browsing_icon
